language: ruby
rvm:
  - 2.2.3
script: rubocop && rspec

# We have to install Rust manually, as Travis does not yet allow multiligual
# builds.
before_install:
  - mkdir ~/rust-installer
  - curl -sL https://static.rust-lang.org/rustup.sh -o ~/rust-installer/rustup.sh
  - sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=nightly -y --disable-sudo 2> /dev/null
