# frozen_string_literal: true

require 'fileutils'

LIB_PATH = 'target/release/libgitignore_binding.dylib'

desc 'Ensure rustc is present and is callable on the current PATH.'
task :check_rustc do
  puts 'Checking for rustc...'
  raise 'Could not find rustc on your path, please check you have it installed.' unless system 'rustc --version'
end

desc 'Ensure cargo is present and is callable on the current PATH.'
task :check_cargo do
  puts 'Checking for cargo...'
  raise 'Could not find cargo on your path, please check you have it installed.' unless system 'cargo --version'
end

desc 'Ensure any previous builds are cleaned up properly.'
task :clean do
  FileUtils.rm_rf(File.join(__dir__, 'target'))
end

desc 'Execute cargo build to construct the dynamic library.'
task build: :clean do
  unless system 'cargo build --release'
    raise 'Could not execute cargo build successfully, please check the logs and try again.'
  end
end

file LIB_PATH => :build

desc 'Build the dynamic library.'
task default: LIB_PATH
